export const ADD_INGREDIENTS = 'ADD_INGREDIENTS'
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'

export const PURCHASE_BURGER_SUCESS = 'PURCHASE_BURGER_SUCESS'
export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED'

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'

export const PURCHASE_INIT = 'PURCHASE_INIT'

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';

export const AUTH_START = 'AUTH_START'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const SET_AUTH_REDICET_PATH ="SET_AUTH_REDICET_PATH"